pub mod card_list;
pub mod chart_page;
pub mod documentation;
pub mod filters_page;
mod general;
pub mod home;
pub mod loading_page;
pub mod modal_page;
pub mod notification_page;
pub mod page_not_found;
pub mod signin;
pub mod signup;
